# CrystalSpace v3.0.0-ALPHA Main Configuration File
# ----------------------------------------
#     This configuration has a pretty      
#    huge amount of documentation, but     
#   if you still have questions, please    
#        ask on BukkitDev! Thanks.

# Debugging mode
debug: false

# Global settings
global:
    # Spacesuit armortype - Does not include helmet
    # "id" if you want to use the ids below
    armortype: id
    chestplate: 133
    leggings: 134
    boots: 135
    # Spacehelmet block id
    helmet: 86
    # Other global settings
    givehelmet: false
    givesuit: false
    # If true, any time a player is in one of the below worlds,
    # they won't drown while wearing the helmet
    drowning:
      stopdrowning: false
      # For example: [spaceworld1,spaceworld2,nonspaceworld]
      worlds: []
